name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.16rc1'

    - name: Build
      run: go build -ldflags="-X 'main.aroVersion=dev' -X 'main.aroDate=$(date '+(%d %b %Y)')'" -o build_test

    - name: Test
      run: go test -v

